CREATE TABLE USER (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100),
    NICK_NAME VARCHAR(100),
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    USER_ROLE VARCHAR(100),
    BASE_ADDRESS VARCHAR(255),
    DETAIL_ADDRESS VARCHAR(255),
    ZIPCODE VARCHAR(100),
    PRIMARY KEY(USER_ID)
);
