CREATE TABLE WORK (
    WORK_ID INT AUTO_INCREMENT,
    WORK_PROFILE_ID INT,
    AUTHOR_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    WORK_STATE INT DEFAULT '0',
    WORK_FLAG INT,
    WORK_TIME DATETIME,
    PRICE INT,
    LOCATION VARCHAR(100),
    PRIMARY KEY (WORK_ID)
);