CREATE TABLE WORK (
    WORK_ID INT AUTO_INCREMENT,
    AUTHOR_ID INT NOT NULL,
    WORK_TYPE VARCHAR(100),
    PRICE INT,
    LOCATION VARCHAR(100),
    CREATED_AT datetime NULL,
    UPDATED_AT datetime NULL,
    PRIMARY KEY (WORK_ID)
);