CREATE TABLE CONTRACT (
    CONTRACT_ID INT AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    WORK_ID INT NOT NULL,
    WORK_PROGRESS TINYINT(1),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    START_DATE DATETIME,
    END_DATE DATETIME,
    PRIMARY KEY (CONTRACT_ID),
    [CONSTRAINT WORK_CONTRACT]
    FOREIGN KEY (WORK_ID)
    REFERENCES WORK(WORK_ID),
    [CONSTRAINT USER_CONTRACT]
    FOREIGN KEY (USER_ID)
    REFERENCES USERS(ID)
);