CREATE TABLE WORK_PROFILE (
    WORK_PROFILE_ID INT AUTO_INCREMENT,
    AUTHOR_ID INT NOT NULL,
    LOCATION varchar(100) NOT NULL,
    WORK_TIME datetime,
    PRICE INT,
    DISCOUNT INT,
    WORK_TYPE VARCHAR(100),
    USE_YN TINYINT(1),
    PRIMARY KEY (WORK_PROFILE_ID)
);