CREATE TABLE CONTRACT (
    CONTRACT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '계약_ID',
    USER_ID INT NOT NULL COMMENT '고객_ID',
    WORK_ID INT NOT NULL COMMENT '작업_ID',
    WORK_PROGRESS TINYINT(1) COMMENT '작업상태',
    CREATED_AT DATETIME COMMENT '생성일',
    UPDATED_AT DATETIME COMMENT '수정일',
    START_DATE DATETIME COMMENT '작업시작일',
    END_DATE DATETIME COMMENT '작업만료일',
    FOREIGN KEY (WORK_ID) REFERENCES WORK(WORK_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);