CREATE TABLE PHOTO_BOARD (
    BOARD_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT,
    MAIN_TYPE VARCHAR(100),
    WORK_TYPE VARCHAR(100),
    MAIN_PHOTO_ID INT,
    READ_COUNT VARCHAR(255) DEFAULT 0,
    CREATED_AT DATETIME COMMENT '생성일',
    UPDATED_AT DATETIME COMMENT '수정일',
    DELETE_YN TINYINT(1) DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    PRIMARY KEY(BOARD_ID)
);
