CREATE TABLE CHAT_FILE (
    CHAT_FILE_ID INT NOT NULL AUTO_INCREMENT,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(255) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    HOST_ID INT,
    DELETED_AT DATETIME COMMENT '삭제일',
    PRIMARY KEY(CHAT_FILE_ID)
);

CREATE TABLE CHAT (
    CHAT_ID INT NOT NULL AUTO_INCREMENT,
    MESSAGE VARCHAR(255),
    CHAT_FILE_ID INT,
    CREATED_AT DATETIME COMMENT '생성일',
    UPDATED_AT DATETIME COMMENT '수정일',
    FOREIGN KEY (CHAT_FILE_ID) REFERENCES CHAT_FILE(CHAT_FILE_ID),
    PRIMARY KEY(CHAT_ID)
);